name: Build wrk with LuaJIT for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v3

      - name: Install cross compile tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            make perl curl bash

      - name: Clone wrk source
        run: |
          git clone https://github.com/wg/wrk.git

      - name: Clone LuaJIT
        run: |
          mkdir -p wrk/ThirdParty
          git clone --branch v2.1 \
            https://github.com/LuaJIT/LuaJIT.git \
            wrk/ThirdParty/LuaJIT-2.1.0-beta3

      - name: Build LuaJIT for ARM64
        run: |
          cd wrk/ThirdParty/LuaJIT-2.1.0-beta3
          sed -i 's/^TARGET=.*$/TARGET=ARM64/' Makefile
          make clean || true
          make CROSS=aarch64-linux-gnu- TARGET=ARM64 HOST_CC=gcc

      - name: Build wrk for ARM64
        run: |
          cd wrk
          make clean || true
          make CC=aarch64-linux-gnu-gcc \
               LUAJIT=ThirdParty/LuaJIT-2.1.0-beta3/src/luajit

      - name: Upload wrk binary
        uses: actions/upload-artifact@v4
        with:
          name: wrk-arm64
          path: wrk/wrk
