name: Build wrk with LuaJIT 2.1.0-beta3 for ARM64 and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 可根据需要修改为主分支名称

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 用于访问 Docker Hub

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tags
        id: tags
        run: |
          DATE=$(date +'%Y%m%d')
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "tags=bailangvvking/wrk:arm64,bailangvvking/wrk:arm64-${DATE},bailangvvking/wrk:arm64-luajit2.1.0-beta3" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          build-args:
            TARGETARCH=arm64
          cache-from: type=registry,ref=bailangvvking/wrk:arm64
          cache-to: type=registry,ref=bailangvvking/wrk:arm64,mode=max

      - name: Verify image architecture and LuaJIT version
        run: |
          docker pull bailangvvking/wrk:arm64
          echo "=== Verify wrk binary architecture ==="
          docker run --rm bailangvvking/wrk:arm64 file /usr/local/bin/wrk
          echo "=== Verify LuaJIT version ==="
          docker run --rm bailangvvking/wrk:arm64 /usr/local/bin/wrk -v
