name: Build & Push wrk (ARM64 with LuaJIT)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. 设置 QEMU 多架构支持
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. 获取当前日期（YYYYMMDD）
      - name: Get build date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      # 6. 构建并推送 ARM64 镜像
      - name: Build and push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            bailangvvking/wrk:arm64
            bailangvvking/wrk:arm64-${{ steps.date.outputs.date }}
