name: Build and Push wrk ARM64 Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu make git

    - name: Clone wrk repository
      run: |
        git clone --depth=1 https://github.com/wg/wrk.git
        cd wrk
        CC=aarch64-linux-gnu-gcc CFLAGS="-march=armv8-a+crypto -mtune=cortex-a53" make
        mv wrk ../wrk   # 编译后的文件移到上层，便于 Docker 构建使用

    - name: Prepare Dockerfile
      run: |
        cat > Dockerfile <<EOF
        FROM alpine:3.19
        RUN apk add --no-cache libgcc
        COPY wrk /usr/local/bin/wrk
        ENTRYPOINT ["/usr/local/bin/wrk"]
        CMD ["--help"]
        EOF

    - name: Build Docker image (ARM64)
      run: |
        docker build -t bailangvvking/custom-wrk:arm64 .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push bailangvvking/custom-wrk:arm64
