name: Build LuaJIT ARM64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: LuaJIT/LuaJIT
          ref: v2.1-20230418-beta3  # 你可以指定具体tag或branch

      - name: Install cross compilation tools and dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            make \
            perl \
            curl \
            git

      - name: Apply patch for ARM64 compatible Makefile
        run: |
          # 修改 Makefile 中的 ARM64 相关编译标志，替换 -march=armv8-a 和 -mtune=cortex-a53
          sed -i -E 's/-march=armv8-a/-march=arm64/g' src/Makefile
          sed -i -E 's/-mtune=cortex-a53/-mtune=generic/g' src/Makefile

      - name: Build LuaJIT for ARM64
        working-directory: ./src
        run: |
          make clean || true
          make \
            CROSS=aarch64-linux-gnu- \
            TARGET=ARM64 \
            CC=aarch64-linux-gnu-gcc \
            CFLAGS="-march=arm64 -mtune=generic -O2 -fPIC -DLUAJIT_USE_ARM64=1"

      - name: Upload compiled libluajit.a
        uses: actions/upload-artifact@v3
        with:
          name: libluajit-arm64
          path: ./src/libluajit.a
