name: Build and Push wrk ARM64 Docker Image

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU (multi-arch build support)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64,linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install cross compile toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu make

      - name: Build wrk for ARM64
        run: |
          CC=aarch64-linux-gnu-gcc make clean || true
          CC=aarch64-linux-gnu-gcc make

      - name: Prepare Dockerfile
        run: |
          cat > Dockerfile <<EOF
          FROM alpine:3.19
          RUN apk update && apk add --no-cache libgcc qemu-user
          COPY wrk /usr/local/bin/wrk
          ENTRYPOINT ["/usr/local/bin/wrk"]
          CMD ["--help"]
          EOF

      - name: Build Docker image for ARM64
        run: |
          docker buildx build --platform linux/arm64 -t yourdockerhubusername/custom-wrk:arm64 --push .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
