name: Build and Push wrk ARM64 Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install cross compile tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu make

    - name: Clone wrk repo
      run: git clone https://github.com/wg/wrk.git

    - name: Build wrk for ARM64
      run: |
        cd wrk
        CC=aarch64-linux-gnu-gcc make clean || true
        CC=aarch64-linux-gnu-gcc make

    - name: Prepare Dockerfile
      run: |
        cat > Dockerfile <<EOF
        FROM alpine:3.19
        RUN apk add --no-cache libgcc
        COPY wrk/wrk /usr/local/bin/wrk
        ENTRYPOINT ["/usr/local/bin/wrk"]
        CMD ["--help"]
        EOF

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image (ARM64)
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t yourdockerhubusername/custom-wrk:arm64 --push .

