name: Build and Push wrk ARM64 Docker Image

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build wrk ARM64 Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t yourname/wrk-luajit:arm64 . --push

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push yourname/wrk-luajit:arm64
